ResearchStory/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'Users/', include(('Users.urls', 'Users'), namespace='Users')),

    path(r'', include(('MainPage.urls', 'MainPage'), namespace='MainPage')),

    path(r'story/', include(('Story.urls', 'Story'), namespace='Story')),

    path(r'comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path(r'password_reset/', include('password_reset.urls')),
    path('accounts/', include('allauth.urls')),
    path('meeting/', include(('meeting.urls', 'meeting'), namespace='meeting')),

    path('', include(('interview.urls', 'interview'), namespace='interview')),
    path(r'forum/', include(('forum.urls', 'forum'), namespace='forum')),

    path(r'', include(('Videos.urls', 'Videos'), namespace='Videos')),

    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Story/urls.py
from django.urls import path, re_path, include

from .views import *
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

app_name = 'Story'
urlpatterns = [
                  path(r'', storyList, name='storyList'),
                  path(r'_sort_by=<str:sort_by>', storyListSortBy, name='storyListSortBy'),
                  path(r'story_id=<int:story_id>', getStory, name='getStory'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>_title=<str:title>', storyFind, name='storyFind'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>', storyListCategorySortBy,
                       name='storyListCategorySortBy'),
                  path(r'category=<str:category>', storyListCategory, name='storyListCategory'),
                  path(r'upload/', upload, name='upload'),
                  path(r'advancedSearch=T', advancedSearch, name='advancedSearch'),
                  path(r'search/', search, name='search'),
                  path(r'edit=<int:story_id>', edit, name='edit'),
                  path(r'delete=<int:story_id>', delete, name="delete"),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
                  re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

from Users import views

app_name = 'Users'

urlpatterns = [
    # Login interface
    path(r'login/', LoginView.as_view(template_name='Users/login.html'), name='login'),

    path(r'logout/', views.logout_view, name='logout'),

    path(r'register/', views.register, name='register'),

    path(r'edit/<int:user_id>/', views.profile_edit, name='edit'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

meeting/urls.py
from django.contrib import admin
from django.urls import path
from meeting.models import Link
from meeting import views

app_name = 'meeting'

urlpatterns = [
    path(r'', views.current_meeting, name='current_meeting'),

    path(r'new_meeting', views.new_meeting, name='new_meeting'),

]

meeting/models.py
from django.db import models
from Users.models import User


class Link(models.Model):
    """create a meeting related table to save the info"""
    meeting_name = models.CharField(max_length=500)
    meeting_link = models.URLField(max_length=2000)
    start_time = models.TimeField(default='12:00:00')
    end_time = models.TimeField(default='12:00:00')
    monday = models.BooleanField(default=False)
    tuesday = models.BooleanField(default=False)
    wednesday = models.BooleanField(default=False)
    thursday = models.BooleanField(default=False)
    friday = models.BooleanField(default=False)
    saturday = models.BooleanField(default=False)
    sunday = models.BooleanField(default=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    data_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-data_added',)

    def __str__(self):
        return self.meeting_name

meeting/views.py
from django.shortcuts import render
from datetime import datetime
from meeting.models import Link
from meeting.meetingforms import MeetingForm
from Users.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse


def time_in_mins(hr, min):
    return hr * 60 + min


def current_meeting(request):
    """ get the current meetings """
    current_time = datetime.now()
    current_hour = current_time.hour
    current_min = current_time.minute
    meeting_list = list(Link.objects.all().order_by('-data_added'))
    current_meetings = []
    for meeting in meeting_list:
        start_time_hour = meeting.start_time.hour
        start_time_min = meeting.start_time.minute
        end_time_hour = meeting.end_time.hour
        end_time_min = meeting.end_time.minute
        day_list = []
        if meeting.monday == True:
            day_list.append('Monday')
        if meeting.tuesday == True:
            day_list.append('Tuesday')
        if meeting.wednesday == True:
            day_list.append('Wednesday')
        if meeting.thursday == True:
            day_list.append('Thursday')
        if meeting.friday == True:
            day_list.append('Friday')
        if meeting.saturday == True:
            day_list.append('Saturday')
        if meeting.sunday == True:
            day_list.append('Sunday')
        if ((day_list.count(current_time.strftime('%A')) != 0)
                and (time_in_mins(end_time_hour, end_time_min)) > time_in_mins(current_hour, current_min)):
            # continue
            current_meetings.append(meeting)
    date_and_time = current_time.strftime("%Y-%m-%d, %A,  %H:%M:%S")
    USER = request.user

    if len(current_meetings) == 0:
        context = {'date_and_time': date_and_time, 'USER': USER, }
        return render(request, 'meeting/nomeetings.html', context)
    else:
        context = {
            'current_meetings': current_meetings,
            'date_and_time': date_and_time,
            'USER': USER,
        }
        return render(request, 'meeting/linktoclick.html', context)


@login_required
def new_meeting(request):
    """add a new meeting for discussion openly"""
    current_time = datetime.now()
    date_and_time = current_time.strftime("%Y-%m-%d, %A,  %H:%M:%S")

    if request.method != 'POST':
        form = MeetingForm()
    else:
        form = MeetingForm(data=request.POST)
        if form.is_valid():
            new_meeting = form.save(commit=False)
            new_meeting.user = request.user
            new_meeting.save()
            return HttpResponseRedirect(reverse('meeting:current_meeting'))
    USER = request.user
    context = {
        'form': form,
        'date_and_time': date_and_time,
        'USER': USER,
    }
    return render(request, 'meeting/new_meeting.html', context)

templates/meeting/linktoclick.html
{% extends 'base.html' %}

{% load static %}
{% block header %}
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/">
            <h2>Meeting To Discuss</h2>
        </a>
        {% if user.is_authenticated %}
            {% if USER.usertype == 'R' %}
                <span>
                    <a href="{% url "meeting:new_meeting" %}"><button type="button" class="btn btn-dark">Add A New Meeting</button></a>
        </span>
            {% endif %}
        {% endif %}
    </nav>
{% endblock header %}


{% block content %}
    {% if user.is_authenticated %}
        <div style="text-align: center;">
            <h2>Current Meetings:</h2>
            <h7>{{ date_and_time }}</h7>
        </div>
        <hr/>
        {% for meeting in current_meetings %}
            <hr/>
            <li>
                <div class="jumbotron">
                    <div style="text-align: center;">
                        <h2><i><b>{{ meeting.meeting_name }}</b></i></h2>
                        <h3>Start Time: {{ meeting.start_time }}</h3>
                        <h3>End Time: {{ meeting.end_time }}</h3>
                        <h6>Organizer: {{ meeting.user }}</h6>
                    </div>
                    <div style="text-align: center;">
                        <a href="{{ meeting.meeting_link }}">
                            <button type="button" class="btn btn-dark">Link to Join:
                                <b>{{ meeting.meeting_name }}</b>
                            </button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    {% endif %}
    <hr/>
    <div class="jumbotron">
        <div style="text-align: center;">
            <h6>Only users who have logged in are allowed can join discussion meetings. </h6>
            <a href="{% url "Users:login" %}"><h5>Login</h5></a>
        </div>
    </div>
{% endblock content %}

templates/meeting/new_meeting.html
{% extends 'base.html' %}

{% block header %}
    <link rel="stylesheet" href="/static/bootstrap-4.6.0-dist/css/timepicker.css"/>
    <script src="/static/bootstrap-4.6.0-dist/js/timepicker.js"></script>
{% endblock header %}

{% block content %}
    <style type="text/css">
        div.content {
            margin: 0 auto;
            padding-top: 10px;
            padding-bottom: 20px;
            padding-left: 15px;
            background-color: rgba(255, 255, 255, 0.8);
        }


    </style>

    <div class="content">
        <div style="text-align: center;">
            <h2>Add a new meeting: </h2>
            <h7>{{ date_and_time }}</h7>
        </div>
        <hr/>
        <div style="text-align: center;">
            <form action="{% url "meeting:new_meeting" %}" method="post">
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="row form-group">
                                <div class="p" style="width:150px;height:40px;float:left;">Meeting name:</div>
                                <input type="text" class="form-control" style="width:340px;height:30px;float:right;"
                                       name="meeting_name" placeholder="" required>
                            </div>
                            <div class="row form-group">
                                <div class="p" style="width:150px;height:40px;float:left;">Meeting link:</div>
                                <input type="text" class="form-control" style="width:340px;height:30px;float:right;"
                                       name="meeting_link" placeholder="http://" required>
                            </div>

                            <div class="row form-group">
                                <div class="p" style="width:150px;height:40px;float:left;">Start at:</div>
                                <input class="form-control" name="start_time"
                                       style="width:310px;height:30px;float:right;" value="12:00:00">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-calendar-date" viewBox="0 0 16 16">
                                    <path d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23z"/>
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                                </svg>
                            </div>

                            <div class="row form-group">
                                <div class="p" style="width:150px;height:40px;float:left;">End at:</div>
                                <input class="form-control" name="end_time" style="width:310px;height:30px;float:right;"
                                       value="12:00:00">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-calendar-date" viewBox="0 0 16 16">
                                    <path d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23z"/>
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                                </svg>
                            </div>
                            <div class="form-inline row" style="margin-left: 20px">

                                {{ form.monday }}
                                <label class="btn" for="btn-check-1">Monday</label>
                                {{ form.tuesday }}
                                <label class="btn" for="btn-check-2">Tuesday</label>
                                {{ form.wednesday }}
                                <label class="btn " for="btn-check-3">Wednesday</label>
                                {{ form.thursday }}
                                <label class="btn" for="btn-check-4">Thursday</label>
                            </div>
                            <div class="form-inline row" style="margin-left: 20px">
                                {{ form.friday }}
                                <label class="btn" for="btn-check-5">Friday</label>
                                {{ form.saturday }}
                                <label class="btn" for="btn-check-6">Saturday</label>
                                {{ form.sunday }}
                                <label class="btn" for="btn-check-7">Sunday</label>
                            </div>
                            <div class="row"></div>
                        </div>
                        <div class="col-xl-6">
                            <div class="img-rounded">
                                <img src="/static/image/meeting2.jpg" class="img-rounded " alt="interview image"
                                     style="width: 480px;height: 350px">
                            </div>
                        </div>
                    </div>
                </div>
                <button name="submit" class="btn btn-primary">Add meeting</button>
            </form>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script>
        $('input').timePicker();
    </script>
{% endblock %}

templates/meeting/nomeetings.html
{% extends 'base.html' %}


{% block header %}




{% endblock header %}


{% block content %}
    <style type="text/css">
        div.content {
            margin: 0 auto;
            padding-top: 10px;
            padding-bottom: 20px;
            padding-left: 15px;
            background-color: rgba(255, 255, 255, 0.8);
        }

    </style>
    <div class="content">
        <nav class="navbar navbar-light bg-transparent">
            <a class="navbar-brand" href="/">

                <h2>Meeting To Discuss</h2>
            </a>
            <span>
                     {% if user.is_authenticated %}
                         {% if USER.usertype == 'R' %}

                             <a href="{% url "meeting:new_meeting" %}"><button type="button" class="btn btn-dark">Add A New
                            Meeting</button></a>
                         {% endif %}
                     {% endif %}
        </span>
        </nav>

        <div style="text-align: center;">
            <h2>No Meetings Currently :)</h2>
            <h7>{{ date_and_time }}</h7>
        </div>
        <hr/>
        {% if user.is_authenticated %}
            {% if USER.usertype == 'R' %}
                <div class="d-flex justify-content-center">
                    <a href="{% url "meeting:new_meeting" %}">
                        <button type="button" class="btn btn-dark">Welcome to create a meeting for online discussion.
                        </button>
                    </a>
                </div>
            {% endif %}
        {% endif %}
        <hr/>
        <br>
        <div class="jumbotron">
            <div style="text-align: center;">
                <h6>Only users who have logged in are allowed can join discussion meetings. </h6>
                <a href="{% url "Users:login" %}"><h5>Login</h5></a>
            </div>
        </div>


    </div>


{% endblock content %}