ResearchStory/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'Users/', include(('Users.urls', 'Users'), namespace='Users')),

    path(r'', include(('MainPage.urls', 'MainPage'), namespace='MainPage')),

    path(r'story/', include(('Story.urls', 'Story'), namespace='Story')),

    path(r'comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path(r'password_reset/', include('password_reset.urls')),
    path('accounts/', include('allauth.urls')),
    path('meeting/', include(('meeting.urls', 'meeting'), namespace='meeting')),

    path('', include(('interview.urls', 'interview'), namespace='interview')),
    path(r'forum/', include(('forum.urls', 'forum'), namespace='forum')),

    path(r'', include(('Videos.urls', 'Videos'), namespace='Videos')),

    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Story/urls.py
from django.urls import path, re_path, include

from .views import *
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

app_name = 'Story'
urlpatterns = [
                  path(r'', storyList, name='storyList'),
                  path(r'_sort_by=<str:sort_by>', storyListSortBy, name='storyListSortBy'),
                  path(r'story_id=<int:story_id>', getStory, name='getStory'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>_title=<str:title>', storyFind, name='storyFind'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>', storyListCategorySortBy,
                       name='storyListCategorySortBy'),
                  path(r'category=<str:category>', storyListCategory, name='storyListCategory'),
                  path(r'upload/', upload, name='upload'),
                  path(r'advancedSearch=T', advancedSearch, name='advancedSearch'),
                  path(r'search/', search, name='search'),
                  path(r'edit=<int:story_id>', edit, name='edit'),
                  path(r'delete=<int:story_id>', delete, name="delete"),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
                  re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

from Users import views

app_name = 'Users'

urlpatterns = [
    # Login interface
    path(r'login/', LoginView.as_view(template_name='Users/login.html'), name='login'),

    path(r'logout/', views.logout_view, name='logout'),

    path(r'register/', views.register, name='register'),

    path(r'edit/<int:user_id>/', views.profile_edit, name='edit'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

Videos/urls.py
from django.urls import path, re_path
from Videos import views
from django.views.static import serve
from django.conf import settings

app_name = 'Videos'
urlpatterns = [
    path('video_list/', views.VideoIndexView.as_view(), name='video_list'),
    path('video_list/<int:video_id>/', views.video_detail, name='video_detail'),
    path('video_list/post_comment/<int:video_id>/', views.post_video_comment, name='video_comment'),
    path('new_video/', views.new_video, name='new_video'),
    path("edit_video/<int:video_id>/", views.edit_video, name='edit_video'),
    path(r'video_delete=<int:video_id>', views.video_delete, name="video_delete"),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

Videos/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from Users.models import User
from Story.models import Story
from django.urls import reverse
from .validators import file_size


class Classification(models.Model):
    """ create a table about classification of Videos"""
    list_display = ('title')
    title = models.CharField(max_length=100, blank=True, null=True)
    status = models.BooleanField(default=True)

    class Meta:
        db_table = 'v_classification'

    def __str__(self):
        return str(self.title)


class Video(models.Model):
    """create a table of video information and its format"""
    title = models.CharField(max_length=228)
    desc = models.TextField(blank=True, null=True)
    url = EmbedVideoField(blank=True, null=True)
    file = models.FileField(upload_to='video/%y', validators=[file_size], blank=True, null=True)
    classification = models.ForeignKey(Classification, on_delete=models.CASCADE, null=True)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-created_time']

    def get_absolute_url(self):
        return reverse('Videos:video_detail', args=[self.id])


class VideoComment(models.Model):
    """A table is to save the information of video related comments"""
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name="video_comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="video_comments")
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return self.content[:30]

Videos/forms.py
from django import forms
from Videos.models import VideoComment, Video, Classification


class VideoCommentForm(forms.ModelForm):
    """create a form for the comment of video"""
    class Meta:
        model = VideoComment
        fields = ['content']


class NewVideoForm(forms.ModelForm):
    """generate a form for uploading a new interview (meeting) video"""
    class Meta:
        model = Video
        fields = [
            'title',
            'desc',
            'url',
            'file',
            'classification',
        ]
        widgets = {'desc': forms.Textarea(attrs={'cols': 60})}

Videos/views.py
from django.shortcuts import render
from Videos.models import Video, Classification, VideoComment
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from Videos.forms import VideoCommentForm, NewVideoForm
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


class VideoIndexView(generic.ListView):
    model = Video
    template_name = 'Videos/video_list.html'
    context_object_name = 'videos'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VideoIndexView, self).get_context_data(**kwargs)
        classification_list = Classification.objects.filter(status=True).values()
        context['classification_list'] = classification_list
        return context

    def get_queryset(self):
        self.c = self.request.GET.get("c", None)
        if self.c:
            classification = get_object_or_404(Classification, pk=self.c)
            return classification.video_set.all().order_by("-created_time")
        else:
            return Video.objects.filter().order_by('-created_time')


def video_detail(request, video_id):
    """showing a video detail on a single page"""
    video = get_object_or_404(Video, id=video_id)
    video_comments = VideoComment.objects.filter(video=video_id)
    video_comment_form = VideoCommentForm()

    context = {'video': video,
               'video_comments': video_comments,
               'video_comment_form': video_comment_form,
               }
    return render(request, 'Videos/video_detail.html', context)


@login_required
def post_video_comment(request, video_id):
    """post a comment under a certain video """
    video = get_object_or_404(Video, id=video_id)
    if request.method == 'POST':
        video_comment_form = VideoCommentForm(data=request.POST)
        if video_comment_form.is_valid():
            new_comment = video_comment_form.save(commit=False)
            new_comment.video = video
            new_comment.user = request.user
            new_comment.save()
            return redirect(video)
        else:
            return render(request, 'Fail/comments_fail.html')
            # return HttpResponse("The content of the form is incorrect, please fill in again. ")
    else:
        return HttpResponse("Only POST requests are accepted for comments.")


@login_required
def new_video(request):
    """add a new interview video (or an open meeting video)"""
    classification = Classification.objects.all().values()
    if request.method != 'POST':
        form = NewVideoForm()
    else:
        form = NewVideoForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.uploader = request.user
            new_form.save()
            return HttpResponseRedirect(reverse("Videos:video_list"))
    context = {"form": form,
               'classification': classification,
               }
    return render(request, 'Videos/new_video.html', context)


@login_required
def edit_video(request, video_id):
    """editing the current video by the video's uploader"""
    video = Video.objects.get(id=video_id)
    classification = Classification.objects.all().values()
    #  Protect page
    if video.uploader != request.user:
        raise Http404
    if request.method == "POST":
        form = NewVideoForm(instance=video, data=request.POST, files=request.FILES)
        if form.is_valid():
            video.title = request.POST['title']
            video.desc = request.POST['desc']
            video.url = request.POST['url']
            if 'file' in request.FILES:
                video.file = request.POST['files']

            video.save()
            # return HttpResponse("edit successful")
            return HttpResponseRedirect(reverse("Videos:video_detail", args=[video_id]))
        else:
            return render(request, 'Fail/comments_fail.html')
            # return HttpResponse("<h1>The content of the form is incorrect, please fill in again.</h1>")
    else:
        form = NewVideoForm(instance=video)
        context = {'video': video, 'classification': classification, 'form': form}
        return render(request, "Videos/edit_video.html", context)


@login_required
def video_delete(request, video_id):
    """delete the video"""
    video = Video.objects.filter(id=video_id)
    if video:
        video.delete()
    return HttpResponseRedirect(reverse("Videos:video_list"))

templates/Videos/edit_video.html
{% extends "base.html" %}
{% load embed_video_tags %}

{% block header %}

{% endblock header %}
{% block content %}
    <style type="text/css">
        div.content {
            margin: 0 auto;
            padding-top: 10px;
            padding-bottom: 20px;
            padding-left: 15px;
            background-color: rgba(255, 255, 255, 0.8);
        }


    </style>
    <div class="content">


        <div class="text">
            <div style="text-align: center;">
                <h3 class="display-4" style="margin-left: 10px">Edit video</h3>
                <h4>
                    <a href="{% url "Videos:video_detail" video.id %}" style="margin-left: 10px">{{ video.title }}</a>
                </h4>
            </div>


            <p class="lead">This is a video edit page, — makes short story video edit. In this page, you will enjoy the
                educational videos.</p>
            <hr class="my-4">
        </div>


        <form action="{% url "Videos:edit_video" video.id %}" method="post" class="form">
            {% csrf_token %}

            <div class="row justify-content-center form-group">
                <div class="p" style="width:70px;height:40px;float:left">Tittle:</div>
                <input type="text" class="form-control" style="width:340px;height:30px;float:right;margin-left: 10px"
                       name='title' placeholder="Username" required value="{{ video.title }}">

            </div>
            <div class="row justify-content-center form-group">
                <div class="p" style="width:70px;height:40px;float:left">Describe:</div>
                <textarea style="max-width:340px" class="form-control" name="desc" aria-label="With textarea"
                          rows="15" placeholder="Please Enter Your desc, adding relevant content about the research story interview or meeting here. ">
                    {{ video.desc }}</textarea>
                {#                <input type="text" class="form-control" style="width:340px;height:90px;float:right;margin-left: 10px"#}
                {#                       name='desc' placeholder="Add some describe of video" required value="{{ video.desc }}">#}

            </div>
                  <div class="row justify-content-center form-group">
                    <div class="p" style="width:70px;height:40px;float:left">Urls:</div>
                    <input type="text" class="form-control"
                           style="width:340px;height:30px;float:right;margin-left: 10px"
                           name='url' placeholder="url" value="{{ video.url }}">
                </div>

                     <div class="row justify-content-center">
                <p style="margin-left: 30px">( Tips: You must choose either a video url link or a file to upload. )</p>
            </div>

                <div class="row justify-content-center form-group">
                    <div class="p" style="width:70px;height:40px;float:left;margin-right: 10px"></div>
                    {{ form.file }}{{ video.file }}
                </div>

            <br>

            <div class="row form-group justify-content-center">
                <div class="p" style="width:110px;height:40px;float:left;margin-right: 30px">Classification:</div>
                {{ form.classification }}
            </div>
            <div style="text-align:center">
                <button class="btn btn-primary " name="submit">SUBMIT</button>

            </div>

        </form>

    </div>
{% endblock content %}

templates/Videos/new_video.html
{% extends 'base.html' %}
{% load embed_video_tags %}


{% block content %}
    <style type="text/css">
        div.content {
            margin: 0 auto;
            padding-top: 10px;
            padding-bottom: 20px;
            padding-left: 15px;
            background-color: rgba(255, 255, 255, 0.8);
        }

    </style>
    <div class="content">
        <div style="text-align: center;">
            <div class="container">

                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    <br>
                    <br>
                    <br>


                    <div class="row justify-content-center form-group">
                        <div class="p" style="width:40px;height:40px;float:left">Title:</div>
                        <input type="text" class="form-control" style="width:300px;height:30px;float:right;"
                               name="title" placeholder="title" required>
{#                        <textarea style="max-width:300px" class="form-control" name="desc" aria-label="With textarea"#}
{#                                  rows="2" placeholder="Please Enter a title" required></textarea>#}
                    </div>

                    <div class="row justify-content-center form-group">
                        <div class="p" style="width:40px;height:40px;float:left">Url:</div>
                        <input type="text" class="form-control" style="width:300px;height:30px;float:right;"
                               name="url" placeholder="url">
                    </div>


                    <div class="row justify-content-center">
                        <p style="margin-left: 30px">( Tips: You must choose either a video url link or a file to
                            upload. )</p>
                    </div>

                              <div class="row  form-group">
                        <div class="col-md-4 offset-md-5">
                            {{ form.file }}
                        </div>
                    </div>
                    <br>


                    <div class="row  form-group">
                        <div class="col-md-4 offset-md-3">
                            <div class="p" style="width:150px;height:40px;float:left;margin-left:10px">Classification:
                            </div>
                            {{ form.classification }}
                        </div>
                    </div>

                    <div class="row justify-content-center form-group">
                        <textarea style="max-width:420px" class="form-control" name="desc" aria-label="With textarea"
                                  rows="20" placeholder="Please enter the description about this video, and adding more relevant content about the research story interview or meeting here."></textarea>
                    </div>


                    <hr/>
                    <button class="btn btn-primary " style="margin-right:50px ">SUBMIT</button>
                </form>

            </div>
        </div>
    </div>

{% endblock content %}

templates/Videos/video_detail.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %}

{% block header %}


{% endblock header %}


{% block content %}
    <style type="text/css">
        div.content {
            margin: 0 auto;
            padding-top: 10px;
            padding-bottom: 20px;
            padding-left: 15px;
            background-color: rgba(255, 255, 255, 0.8);
        }

    </style>

    <hr/>
    <div class="content">

    <span style="margin-left: 25px">
     <a class="ui red label" href="{% url "Videos:video_list" %}">
            <button class="btn btn-secondary">ALL</button>
     </a>
     <a href="{% url "Videos:new_video" %}"><button type="button" class="btn btn-dark" style="margin-left: 780px">Add A New Interview Video
                            </button></a>
    </span>
    <hr/>
    <br>
        <h3 class="text-center mt-2 mb-2" style="margin-left: 20px">{{ video.title }}</h3>
    <br>
        <div style="text-align: center;">
            <div class="container">
                {% if video.file %}
                    <video class="embed-responsive embed-responsive-16by9" controls="controls">
                        <source src="{{ video.file.url }}" type="video/mp4"/>
                    </video>
                {% else %}
                    {% video video.url '1000x600' %}
                {% endif %}
                <hr/>
                <div class="row">
                    <div class="col-md-9 "><p class="mt-2 mb-2 text-left">Title: {{ video.title }}</p></div>
                    <div class="col-md-1"></div>
                    <div class="col-md 4">
                        <div class="row">
                            {% if video.uploader.id == user.id %}
                                <p style="margin-right: 20px"><a href="{% url "Videos:edit_video" video.id %}">Edit</a>
                                </p>
                                <p><a href="{% url "Videos:video_delete" video.id %}">Delete</a></p>
                            {% endif %}</div>
                    </div>
                </div>
                <hr/>

                <div class="row">
                    <div class="col-lg-2 img">
                        <img src="{{ video.uploader.profile.avatar.url }} " style="width: 60px; height:55px;" class="round_icon">
                    </div>
                    <div class="col-lg-10 text-left">
                        <p>Uploader: {{ video.uploader }}</p>
                        <p>Published on {{ video.created_time|date:"Y-m-d H:i:s" }} </p>
                        <p>Research Area: {{ video.classification }}</p>
                        <p>{{ video.desc }}</p>
                    </div>

                </div>

            </div>
        </div>
            </div>
        </div>

        <hr/>
        <h5>{{ video_comments.count }} Comments</h5>
        {% if user.is_authenticated %}
            <div>
                <form action="{% url "Videos:video_comment" video.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                    <textarea type="text" class="form-control" id="content" name="content" rows="2"
                              placeholder="Please enter a comment"
                              style="width:1050px;height: 100px;margin-left: 20px;margin-right: 20px"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary right " style="margin-left: 900px">SUBMIT</button>
                </form>
            </div>

            <br>
        {% else %}
            <br>
            <h5 class="row justify-content-center">
                Please <a href="{% url 'Users:login' %}"> login </a> to reply.
            </h5>
            <br>
        {% endif %}

        <div>
            {% for comment in video_comments %}
                <hr>
                <p>
                    <strong style="color: black">
                        {{ comment.user }}
                    </strong>
                    <span style="color: green">
                    {{ comment.created_time|date:"Y-m-d H:i:s" }}
                </span>
                </p>
                <pre style="font-family: inherit; font-size: 1em;">{{ comment.content }}</pre>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/Videos/video_list.html
{% extends 'base.html' %}

{% load embed_video_tags %}
{% block header %}

    <hr/>
    <div class="text">
        <h1 class="display-4" style="margin-left: 25px">Video</h1>
        <p class="lead" style="margin-left: 20px">This is a video unit, — makes short research story video sharing, discussion and uploading. In this page,
            you will enjoy the research and educational videos.</p>
    </div>
    <br>
    <div class="classification">
        <h3 class=" mb-2 mb-2">
            <a class="ui red label" style="margin-left: 20px"href="{% url "Videos:video_list" %}">
                <button class="btn btn-secondary">ALL</button>
            </a>
            {% for item in classification_list %}

                <a class="ui label" href="?c={{ item.id }}" style="margin-left: 5px">
                    <button class="btn btn-secondary">{{ item.title }} </button>
                </a>
            {% endfor %}
        </h3>
        <hr/>
    </div>

    <span>
     <a href="{% url "Videos:new_video" %}"><button type="button" class="btn btn-dark" style="margin-left: 880px">Add A New Interview Video</button></a>
    </span>
    <hr/>


{% endblock header %}


{% block content %}
    <style type="text/css">

        div.content {
            display: grid;
            grid-template-columns: 33.33% 33.33% 33.33%;
            grid-template-rows: 300px 300px 300px;
            grid-row-gap: 20px;
            grid-column-gap: 20px;
        }

        div.product-buyer-name {
            max-width: 400px;
            max-height: 60px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

    </style>
    <div class="container">

        <div class="content">
            {% for item in videos %}
                <div class="card ">
                    {% if item.file %}
                        <div class="card-header product-buyer-name" style="height: 60px"><a
                                href="{% url "Videos:video_detail" item.id %}">{{ item.title }}</a></div>
                        <div class="card-body">
                            <video class="embed-responsive embed-responsive-16by9" autoplay loop muted
                                   controls="controls">
                                <source src="{{ item.file.url }}" type="video/mp4"/>
                            </video>
                        </div>
                        <div class="card-footer">
                            <h7>Post on {{ item.created_time|date:"Y-m-d H:i" }} by {{ item.uploader }}</h7>
                        </div>
                    {% else %}
                        <div class="card-header product-buyer-name" style="height: 60px"><a
                                href="{% url "Videos:video_detail" item.id %}">{{ item.title }}</a></div>
                        <div class="card-body">
                            {% video item.url '300x180' %}

                        </div>
                        <div class="card-footer">
                            <h7>Post on {{ item.created_time|date:"Y-m-d H:i" }} by {{ item.uploader }}</h7>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}