ResearchStory/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'Users/', include(('Users.urls', 'Users'), namespace='Users')),

    path(r'', include(('MainPage.urls', 'MainPage'), namespace='MainPage')),

    path(r'story/', include(('Story.urls', 'Story'), namespace='Story')),

    path(r'comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path(r'password_reset/', include('password_reset.urls')),
    path('accounts/', include('allauth.urls')),
    path('meeting/', include(('meeting.urls', 'meeting'), namespace='meeting')),

    path('', include(('interview.urls', 'interview'), namespace='interview')),
    path(r'forum/', include(('forum.urls', 'forum'), namespace='forum')),

    path(r'', include(('Videos.urls', 'Videos'), namespace='Videos')),

    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Story/urls.py
from django.urls import path, re_path, include

from .views import *
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

app_name = 'Story'
urlpatterns = [
                  path(r'', storyList, name='storyList'),
                  path(r'_sort_by=<str:sort_by>', storyListSortBy, name='storyListSortBy'),
                  path(r'story_id=<int:story_id>', getStory, name='getStory'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>_title=<str:title>', storyFind, name='storyFind'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>', storyListCategorySortBy,
                       name='storyListCategorySortBy'),
                  path(r'category=<str:category>', storyListCategory, name='storyListCategory'),
                  path(r'upload/', upload, name='upload'),
                  path(r'advancedSearch=T', advancedSearch, name='advancedSearch'),
                  path(r'search/', search, name='search'),
                  path(r'edit=<int:story_id>', edit, name='edit'),
                  path(r'delete=<int:story_id>', delete, name="delete"),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
                  re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

from Users import views

app_name = 'Users'

urlpatterns = [
    # Login interface
    path(r'login/', LoginView.as_view(template_name='Users/login.html'), name='login'),

    path(r'logout/', views.logout_view, name='logout'),

    path(r'register/', views.register, name='register'),

    path(r'edit/<int:user_id>/', views.profile_edit, name='edit'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

Videos/urls.py
from django.urls import path, re_path
from Videos import views
from django.views.static import serve
from django.conf import settings

app_name = 'Videos'
urlpatterns = [
    path('video_list/', views.VideoIndexView.as_view(), name='video_list'),
    path('video_list/<int:video_id>/', views.video_detail, name='video_detail'),
    path('video_list/post_comment/<int:video_id>/', views.post_video_comment, name='video_comment'),
    path('new_video/', views.new_video, name='new_video'),
    path("edit_video/<int:video_id>/", views.edit_video, name='edit_video'),
    path(r'video_delete=<int:video_id>', views.video_delete, name="video_delete"),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

forum/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from forum import views
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf import settings

app_name = 'forum'

urlpatterns = [
    path(r'', forumList, name='forumList'),
    path(r'forum_id=<int:forum_id>', get_forum, name='get_forum'),
    path(r'post_forum/<int:forum_id>', post_forum, name='post_forum'),
    path(r'post_forum/<int:forum_id>/<int:parent_forumcomment_id>', post_forum, name='forum_reply'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from notice import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

Story/models.py
import os

from django.db import models
from django.utils.timezone import now
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from Users.models import User

Choices = (('ComputerScience', 'ComputerScience'),
           ("Engineering", "Engineering"),
           ("Law", "Law"),
           ("Medicine", "Medicine"),
           ("Science", "Science"),
           ("Art", "Art"),
           ("Business", "Business"))


class Story(models.Model):
    """create a table of a research story"""
    title_name = models.CharField(verbose_name="title", max_length=100)
    created_time = models.DateTimeField(verbose_name='publish time', auto_now_add=True)
    category = models.CharField(verbose_name="category", max_length=100,
                                choices=Choices,
                                blank=False, null=True)
    views = models.PositiveIntegerField(verbose_name='views number', default=0, auto_created=True)
    img = models.ImageField(verbose_name="front page", upload_to='img/', null=True)
    text = RichTextField()

    video = models.URLField(verbose_name="video", blank=True, null=True)
    paper_link = models.URLField(verbose_name="paper_link", null=True, blank=True)

    author = models.CharField(verbose_name="author", max_length=100, default='author')
    author_intro = models.CharField(verbose_name="author_intro", max_length=1000, default='author introduction')
    background = models.CharField(verbose_name="background", max_length=1000, default='background')
    tags = models.CharField(verbose_name="tags", max_length=100, default=category)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1', null=True)

    def __str__(self):
        return self.title_name

    def viewed(self):
        """
        views add one each use
        """
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name_plural = 'Stories'

    def get_absolute_url(self):
        """get the url of a detail of story page and go back the page after some operation"""
        return reverse('Story:getStory', args=[self.id])

Story/views.py
import os
import re
from datetime import datetime
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm
from interview.models import Interview
from .models import Story
from .storyform import StoryForm, AdvancedSearchForm
from ResearchStory.settings import MEDIA_ROOT
from Users.models import User


def edit(request, story_id):
    """
    :param story_id: id in Story database
    This function is used to edit existed story
    """
    story = Story.objects.get(id=story_id)
    if request.method == "GET":
        form = StoryForm(instance=story)
        return render(request, 'edit.html', locals())
    elif request.method == "POST":
        kwargs = {}
        form = StoryForm(instance=story, data=request.POST)
        mistake = False

        if request.POST.get('title'):
            story.title_name = request.POST.get('title')
        else:
            kwargs["title"] = "You must write title name."
            mistake = True

        story.category = request.POST.get('category')

        if request.POST.get('text'):
            story.text = request.POST.get('text')
        else:
            kwargs["text"] = "You must write something in text form."
            mistake = True

        story.video = request.POST.get('videoUrl')
        story.paper_link = request.POST.get('paperLink')

        if request.FILES.get('img'):
            f = request.FILES['img']
            filepath = os.path.join(MEDIA_ROOT, 'img/' + f.name)
            with open(filepath, 'wb') as fp:
                for info in f.chunks():
                    fp.write(info)
            story.img = 'img/' + f.name
        else:
            story.img = story.img

        if request.POST.get('author'):
            story.author = request.POST.get('author')
        else:
            user = request.user
            story.author = user.username

        story.author_intro = request.POST.get('author_intro')

        if request.POST.get('background'):
            story.background = request.POST.get('background')
        else:
            kwargs["background"] = "You must provide a reseach background."
            mistake = True
        story.tags = request.POST.get('tags')
        story.user = request.user
        if not mistake:
            story.save()
            return HttpResponseRedirect(reverse("Story:getStory", args=[story_id]))
        else:
            return render(request, "Fail/upload_fail.html", kwargs)


def upload(request):
    """
    This function is used to upload a new story
    """
    if request.method == "GET":
        form = StoryForm()
        return render(request, 'upload.html', locals())
    elif request.method == "POST":
        kwargs = {}
        form = StoryForm(data=request.POST)
        story = Story()
        mistake = False

        if request.POST.get('title'):
            story.title_name = request.POST.get('title')
        else:
            kwargs["title"] = "You must write title name."
            mistake = True

        if request.POST.get('category'):
            story.category = request.POST.get('category')
        else:
            kwargs["category"] = "You must choose a category."
            mistake = True

        if request.POST.get('text'):
            story.text = request.POST.get('text')
        else:
            kwargs["text"] = "You must write something in text form."
            mistake = True

        if request.POST.get('background'):
            story.background = request.POST.get('background')
        else:
            kwargs["background"] = "You must provide a reseach background."
            mistake = True

        if request.POST.get('author'):
            story.author = request.POST.get('author')
        else:
            user = request.user
            story.author = user.username

        if request.POST.get("author_intro"):
            story.author_intro = request.POST.get('author_intro')
        else:
            story.author_intro = "This author does not introduce himself/herself."

        if request.FILES.get('img'):
            f = request.FILES['img']
            filepath = os.path.join(MEDIA_ROOT, 'img/' + f.name)
            with open(filepath, 'wb') as fp:
                for info in f.chunks():
                    fp.write(info)
            story.img = 'img/' + f.name
        else:
            story.img = "img/default.png"

        story.tags = request.POST.get('tags')
        story.video = request.POST.get('videoUrl')
        story.paper_link = request.POST.get('paperLink')
        story.user = request.user

        if not mistake:
            story.save()
            return HttpResponseRedirect(reverse("Story:storyList"))
        else:
            return render(request, "Fail/upload_fail.html", kwargs)


def delete(request, story_id):
    """
        :param story_id: id in Story database
        This function is used to delete existed story
    """
    story = Story.objects.filter(id=story_id)
    if story:
        story.delete()
    return HttpResponseRedirect(reverse("Story:storyList"))


def search(request):
    """
        This function is used to search story by title name
    """
    if request.method == "POST":
        keyword = request.POST.get("keyword")

        que = Q()
        for word in keyword.split():
            que &= Q(title_name__icontains=word)

        story = Story.objects.filter(que)
        kwargs = {
            "story": story,
        }
        return render(request, 'story.html', kwargs)


def advancedSearch(request):
    """
        This function is used to search a story by
        title name, category, time and author name.
    """
    if request.method == "GET":
        form = AdvancedSearchForm()
        return render(request, 'advancedSearchPage.html', locals())
    elif request.method == "POST":
        keyword = request.POST.get("keyword")
        keyword_negate = request.POST.get("keyword_negate")

        operator1 = request.POST.get("operator1")
        category_negate = request.POST.get("category_negate")

        category = request.POST.get("category")

        operator2 = request.POST.get("operator2")

        start_at = request.POST.get("start_at")
        end_at = request.POST.get("end_at")
        time_negate = request.POST.get("time_negate")
        sort = request.POST.get("sort")

        author_name = request.POST.get("author_name")

        que = Q()
        if author_name != '':
            for word in author_name.split():
                que &= Q(author__icontains=word)

        if keyword != '':
            for word in keyword.split():
                que &= Q(title_name__icontains=word)
            if keyword_negate == "on":
                que = ~que

        if category != "ALL":
            if operator1 == "AND":
                que &= Q(category=category)
            else:
                que |= Q(category=category)
        if category_negate == "on":
            que = ~que

        if operator2 == "AND":
            que &= Q(created_time__range=(start_at, end_at))
        else:
            que |= Q(created_time__range=(start_at, end_at))
        if time_negate == "on":
            que = ~que

        story = Story.objects.filter(que)
        if (sort == "hot"):
            story = story.order_by("-views")
        kwargs = {
            "story": story,
        }

        return render(request, 'story.html', kwargs)


def storyList(request):
    """
        This function is used to search a story by
        title name, category, time and author name.
    """
    if request.method == "GET":
        story = Story.objects.filter().order_by('-created_time')
        kwarg = {
            "story": story,
        }
        return render(request, 'story.html', kwarg)
    elif request.method == "POST":
        method = request.POST.get("sort_by")
        story = request.POST.get("story")
        if method == "time":
            story.order_by("-created_time")
        elif method == "hot":
            story.order_by("-views")
        kwarg = {
            "story": story,
        }
        return render(request, 'story.html', kwarg)


def storyListSortBy(request, sort_by):
    """
    :param sort_by: "time" or "hot"
    This function can sort the story by time or views
    """
    story = Story.objects.filter()
    if sort_by == "time":
        story = story.order_by("-created_time")
    elif sort_by == "hot":
        story = story.order_by("-views")
    print(story)
    kwarg = {
        "story": story,
    }
    return render(request, 'story.html', kwarg)


def storyListCategory(request, category):
    """
    :param category: different category
    This function can sort the story by category
    """
    if request.method == "GET":
        story = Story.objects.filter(category=category).order_by('-created_time')
        kwarg = {
            "story": story,
        }
        return render(request, 'story.html', kwarg)
    elif request.method == "POST":
        method = request.POST.get("sort_by")
        story = request.POST.get("story")
        if method == "time":
            story.order_by("-created_time")
        elif method == "hot":
            story.order_by("-views")
        kwarg = {
            "story": story,
        }
        return render(request, 'story.html', kwarg)


def storyListCategorySortBy(request, category, sort_by):
    """
    :param category:  different category
    :param sort_by: "time" or "hot"
    This function sort the story by category and time or views
    """
    story = Story.objects.filter(category=category)
    if sort_by == "time":
        story = story.order_by("-created_time")
    elif sort_by == "hot":
        story = story.order_by("-views")
    kwarg = {
        "story": story,
    }
    return render(request, 'story.html', kwarg)


def storyFind(request, category, sort_by, title):
    """

templates/article.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <main class="r_box">
        {% for list in pageInfo.object_list %}
            <li>
                <i><a href="{% url 'detail' id list.id %}">
                    {% if list.articlephoto %}
                        <img src="{{ list.articlephoto.url }}">
                    {% else %}
                        <img src="{% static 'images/pic.png' %}">
                    {% endif %}
                </a></i>
                <h3>
                    <a href="{% url 'detail' id list.id %}">{{ list.title }}</a>
                </h3>
                <p>{{ list.content|safe }}</p>
            </li>
        {% endfor %}


        <div class="pagelist">
            {% if pageInfo.has_previous %}
                <a href="{% url 'article' id pageInfo.previous_page_number %}">上一页</a>
            {% endif %}

            {% if pageInfo.object_list %}
                {% for page in pageInfo.paginator.page_range %}
                    {% if pageInfo.number == page %}
                        <a href="javascript:;" class="curPage">{{ page }}</a>
                    {% else %}
                        <a href="{% url 'article' id page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% if pageInfo.has_next %}
                <a href="{% url 'article' id pageInfo.next_page_number %}">下一页</a>
            {% endif %}
        </div>
    </main>

{% endblock %}

templates/base.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<style type="text/css">
    body {
        margin: 0;
        padding: 0;
        font-family: sans-serif;
        background: url("/static/assets/img/homehome.jpg") no-repeat center 0px;
        background-size: cover;
    <!-- width: 100 %;
    --> <!-- height: 40 %;
    --> background-position: center 0;
        background-repeat: no-repeat;
        background-attachment: fixed;
        -webkit-background-size: cover;
        -o-background-size: cover;
        -moz-background-size: cover;
        -ms-background-size: cover;

    }
</style>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Research stories</title>

    <link rel="stylesheet" href="{% static 'bootstrap-4.6.0-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>


<body>

<div class="container " style="background-color: transparent">

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
        <a class="navbar-brand mb-md-0" href="#">Research</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" ariaik]
        '
        MK<4 -label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active" style="">
                    <a class="nav-link" href="{% url 'MainPage:index' %}"> Home <span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url "Story:storyList" %}"> Story <span
                            class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Research area
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'Story:storyListCategory' 'ComputerScience' %}">ComputerScience</a>
                        <a class="dropdown-item" href="{% url 'Story:storyListCategory' 'Science' %}">Science</a>
                        <a class="dropdown-item"
                           href="{% url 'Story:storyListCategory' 'Engineering' %}">Engineering</a>
                        <a class="dropdown-item" href="{% url 'Story:storyListCategory' 'Law' %}">Law</a>
                        <a class="dropdown-item" href="{% url 'Story:storyListCategory' 'Medicine' %}">Medicine</a>
                        <a class="dropdown-item" href="{% url 'Story:storyListCategory' 'Business' %}">Business</a>
                        <a class="dropdown-item" href="{% url 'Story:storyListCategory' 'Art' %}">Art</a>
                    </div>
                </li>
                {% if user.is_authenticated %}
                    {% if user.usertype == 'R' %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'Story:upload' %}">Add story<span
                                    class="sr-only">(current)</span></a>
                        </li>
                    {% endif %}
                {% endif %}


                <li class="nav-item active">
                    <a class="nav-link" href="{% url "meeting:current_meeting" %}"> Meeting <span
                            class="sr-only"></span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url "forum:forumList" %}"> Forum <span
                            class="sr-only"></span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url "Videos:video_list" %}"> Video <span
                            class="sr-only"></span></a>
                </li>


            </ul>

            <form class="form-inline my-2 my-lg-0">


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle"
                       data-toggle="dropdown"
                       style="height: 60px">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                            <path fill-rule="evenodd"
                                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                        </svg>
                        <span style="font-size: 15px">
                                    <i>username</i>
                                </span>
                    </a>
                    <div class="dropdown-menu pull-right"
                         style="background: #FFFFFF;width: 320px;overflow: hidden">

                        <div style="margin-top: 16px;border-bottom: 1px solid #eeeeee">
                            <div style="text-align: center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd"
                                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </div>
                            <div style="color: #323534;text-align: center;line-height: 36px;font-size: 15px">
                                {% if user.is_authenticated %}
                                    <a>Hello, {{ user.username }}.</a>
                                    <a href="{% url 'Users:logout' %}">Logout</a>
                                {% else %}
                                    <a href="{% url 'Users:register' %}">Register</a>
                                    <a href="{% url 'Users:login' %}">Login</a>
                                {% endif %}
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if unread_count %}
                                    <svg viewBox="0 0 8 8"
                                         width="8px"
                                         height="8px">
                                        <circle cx="4"
                                                cy="4"
                                                r="4"
                                                fill="#ff6b6b"
                                        ></circle>
                                    </svg>
                                {% endif %}
                                {#                            {{ user.username }}#}
                            </a>

                            <div class="row" style="margin-left: 15px;margin-right: 15px;margin-top: 10px">
                                <div class="col-md-4 text-center grid">
                                    <i class="fa fa-user" style="font-size: 25px;line-height: 45px;"></i>
                                    <p style="padding: 0px;margin-top: 6px;margin-bottom: 10px;font-size: 12px">
                                        <a href="{% url 'Users:edit' user.id %}">Profile</a></p>
                                </div>
                                <div class="col-md-4 text-center grid">
                                    <i class="fa fa-gear" style="font-size: 25px;line-height: 45px;"></i>
                                    <p style="padding: 0px;margin-top: 6px;margin-bottom: 10px;font-size: 12px">
                                        Account management</p>
                                </div>
                                <div class="col-md-4 text-center grid">
                                    <i class="fa fa-key" style="font-size: 25px;line-height: 45px;"></i>
                                    <p style="padding: 0px;margin-top: 6px;margin-bottom: 10px;font-size: 12px">
                                        Change Password</p>
                                </div>
                            </div>
                            <div class="row" style="margin-left: 15px;margin-right: 15px;margin-top: 10px">
                                <div class="col-md-4 text-center grid">
                                    <i class="fa fa-user-circle" style="font-size: 25px;line-height: 45px;"></i>
                                    <p style="padding: 0px;margin-top: 6px;margin-bottom: 10px;font-size: 12px">
                                        Modify avatar</p>
                                </div>

                                <div class="col-md-4 text-center grid">
                                    <i class="fa fa-comments" style="font-size: 25px;line-height: 45px;"></i>

                                    <p style="padding: 0px;margin-top: 6px;margin-bottom: 10px;font-size: 12px">
                                        <a href="{% url "notice:list" %}">Message
                                            {% if unread_count %}
                                                <svg viewBox="0 0 8 8"
                                                     width="8px"
                                                     height="8px">
                                                    <circle cx="4"
                                                            cy="4"
                                                            r="4"
                                                            fill="#ff6b6b"
                                                    ></circle>
                                                </svg>
                                                <span class="badge-danger">{{ unread_count }}</span>
                                            {% endif %}
                                        </a>
                                    </p>
                                </div>
                                <div class="col-md-4 text-center grid">
                                    <i class="fa fa-heart-o" style="font-size: 25px;line-height: 45px;"></i>
                                    <p style="padding: 0px;margin-top: 6px;margin-bottom: 10px;font-size: 12px">
                                        Help</p>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </li>
            </form>
        </div>
    </nav>

</div>
</div>

<div class="container">

    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>

        {% block content %}
        {% endblock content %}

    </div>

</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>
{% block js %}{% endblock %}

</html>