MainPage/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    # 主页
    # path('index/', views.index, name='index'),

    url(r'^$', views.index, name='index'),

]

ResearchStory/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'Users/', include(('Users.urls', 'Users'), namespace='Users')),

    path(r'', include(('MainPage.urls', 'MainPage'), namespace='MainPage')),

    path(r'story/', include(('Story.urls', 'Story'), namespace='Story')),

    path(r'comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path(r'password_reset/', include('password_reset.urls')),
    path('accounts/', include('allauth.urls')),
    path('meeting/', include(('meeting.urls', 'meeting'), namespace='meeting')),

    path('', include(('interview.urls', 'interview'), namespace='interview')),
    path(r'forum/', include(('forum.urls', 'forum'), namespace='forum')),

    path(r'', include(('Videos.urls', 'Videos'), namespace='Videos')),

    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Story/urls.py
from django.urls import path, re_path, include

from .views import *
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

app_name = 'Story'
urlpatterns = [
                  path(r'', storyList, name='storyList'),
                  path(r'_sort_by=<str:sort_by>', storyListSortBy, name='storyListSortBy'),
                  path(r'story_id=<int:story_id>', getStory, name='getStory'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>_title=<str:title>', storyFind, name='storyFind'),
                  path(r'category=<str:category>_sort_by=<str:sort_by>', storyListCategorySortBy,
                       name='storyListCategorySortBy'),
                  path(r'category=<str:category>', storyListCategory, name='storyListCategory'),
                  path(r'upload/', upload, name='upload'),
                  path(r'advancedSearch=T', advancedSearch, name='advancedSearch'),
                  path(r'search/', search, name='search'),
                  path(r'edit=<int:story_id>', edit, name='edit'),
                  path(r'delete=<int:story_id>', delete, name="delete"),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
                  re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.contrib import admin
from django.views.static import serve
from django.conf import settings

from Users import views

app_name = 'Users'

urlpatterns = [
    # Login interface
    path(r'login/', LoginView.as_view(template_name='Users/login.html'), name='login'),

    path(r'logout/', views.logout_view, name='logout'),

    path(r'register/', views.register, name='register'),

    path(r'edit/<int:user_id>/', views.profile_edit, name='edit'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]

MainPage/views.py
from django.shortcuts import render


def index(request):
    """homepage"""

    return render(request, 'index.html')

templates/MainPage/base.html
<p>

    <a href="{% url "MainPage:index" %}">Research Story</a> -

    {% if user.is_authenticated %}

        Hello, {{ user.username }}
        <a href="{% url "Users:logout" %}">Logout</a>

    {% else %}

        <a href="{% url "Users:login" %}">Login</a>
        <a href="{% url "Users:register" %}">Register</a>

    {% endif %}


</p>

{% block content %}{% endblock content %}

templates/MainPage/base1.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>


<body>


<nav class="navbar navbar-default navbar-static-top">
    <div class="container">


        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="#">
                Research STORY</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="{% url 'MainPage:index' %}">Home</a></li>
            </ul>


            <ul class="nav navbar-nav">
                <li><a href="#">Story</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li><a href="#">Q&A</a></li>
            </ul>


            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'Users:logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'Users:register' %}">Register</a></li>
                    <li><a href="{% url 'Users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>


<div class="container">

    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>

</div>

</body>
</html>

templates/MainPage/index.html
{% extends 'MainPage/base.html' %}

{% block content %}
    <div>
        <h1>Follow your passion for research.</h1>
        <h2>Immerse yourself in the innovative and interesting research stories.</h2>
         <h2>Extensive video resources and freely developed discussion environment.</h2>

    </div>

{% endblock content %}

templates/MainPage/index1.html
{% extends 'MainPage/base1.html' %}

{% block header %}
    <div class="jumbotron">

        <h1>Follow your passion for research.</h1>
    </div>

{% endblock header %}



{% block content %}
    <h2>
        <a href="{% url 'Users:register' %}">Register an account</a> Immerse yourself in the innovative and interesting
        research stories.
    </h2>
    <h2>
        Extensive video resources and freely developed discussion environment.
    </h2>

{% endblock content %}